#!/bin/bash

sudo cat /proc/acpi/bbswitch
tee /proc/acpi/bbswitch <<< ON
sudo cat /proc/acpi/bbswitch
prime-select nvidia
prime-select query
# sudo prime-select query
glxinfo | grep OpenGL
# pkill -u nin
pkill -u onin

