#!/bin/bash

# Author AVS 31 Aug 2015




if [ "$(whoami)" = "root" ]
then
    echo "Now I'll open main script. Modify it on you own if need"
    sleep 1
    nano setup
    chmod +rx setup
    ./setup
else
    echo "Run this under root!"
    sleep 1
    exit 0
fi
